# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ihsagui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(804, 619)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 80, 221, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(140, 20, 501, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(578, 518, 184, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Oblicz = QtGui.QPushButton(self.layoutWidget)
        self.Oblicz.setObjectName(_fromUtf8("Oblicz"))
        self.horizontalLayout.addWidget(self.Oblicz)
        self.Zamknij = QtGui.QPushButton(self.layoutWidget)
        self.Zamknij.setObjectName(_fromUtf8("Zamknij"))
        self.horizontalLayout.addWidget(self.Zamknij)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(450, 140, 258, 217))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_4.addWidget(self.label_10)
        self.listView = QtGui.QListView(self.layoutWidget1)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.verticalLayout_4.addWidget(self.listView)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(90, 100, 100, 201))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 100, 61, 206))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.dg1 = QtGui.QSpinBox(self.layoutWidget3)
        self.dg1.setObjectName(_fromUtf8("dg1"))
        self.verticalLayout.addWidget(self.dg1)
        self.gg1 = QtGui.QSpinBox(self.layoutWidget3)
        self.gg1.setObjectName(_fromUtf8("gg1"))
        self.verticalLayout.addWidget(self.gg1)
        self.dg2 = QtGui.QSpinBox(self.layoutWidget3)
        self.dg2.setObjectName(_fromUtf8("dg2"))
        self.verticalLayout.addWidget(self.dg2)
        self.gg2 = QtGui.QSpinBox(self.layoutWidget3)
        self.gg2.setObjectName(_fromUtf8("gg2"))
        self.verticalLayout.addWidget(self.gg2)
        self.dg3 = QtGui.QSpinBox(self.layoutWidget3)
        self.dg3.setObjectName(_fromUtf8("dg3"))
        self.verticalLayout.addWidget(self.dg3)
        self.gg3 = QtGui.QSpinBox(self.layoutWidget3)
        self.gg3.setObjectName(_fromUtf8("gg3"))
        self.verticalLayout.addWidget(self.gg3)
        self.layoutWidget4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(41, 321, 307, 112))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_8 = QtGui.QLabel(self.layoutWidget4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_5.addWidget(self.label_8)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.chooseCamelFunction = QtGui.QRadioButton(self.layoutWidget4)
        self.chooseCamelFunction.setObjectName(_fromUtf8("chooseCamelFunction"))
        self.verticalLayout_3.addWidget(self.chooseCamelFunction)
        self.insertOwnFunction = QtGui.QRadioButton(self.layoutWidget4)
        self.insertOwnFunction.setObjectName(_fromUtf8("insertOwnFunction"))
        self.verticalLayout_3.addWidget(self.insertOwnFunction)
        self.ownFunction = QtGui.QLineEdit(self.layoutWidget4)
        self.ownFunction.setObjectName(_fromUtf8("ownFunction"))
        self.verticalLayout_3.addWidget(self.ownFunction)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "IHS", None))
        self.label_7.setText(_translate("MainWindow", "Podaj dolne i górne granice zmiennych", None))
        self.label_9.setText(_translate("MainWindow", "Program wylicza minima funkcji z wykorzystaniem algorytmu Improved Harmony Search", None))
        self.Oblicz.setText(_translate("MainWindow", "Oblicz", None))
        self.Zamknij.setText(_translate("MainWindow", "Zamknij", None))
        self.label_10.setText(_translate("MainWindow", "Obliczone wartości", None))
        self.label.setText(_translate("MainWindow", "Dolna granica x1", None))
        self.label_2.setText(_translate("MainWindow", "Górna granica x1", None))
        self.label_3.setText(_translate("MainWindow", "Dolna granica x2", None))
        self.label_4.setText(_translate("MainWindow", "Górna granica x2", None))
        self.label_5.setText(_translate("MainWindow", "Dolna granica x3", None))
        self.label_6.setText(_translate("MainWindow", "Górna granica x3", None))
        self.label_8.setText(_translate("MainWindow", "Wybierz funkcję, której minima mają zostać obliczone:", None))
        self.chooseCamelFunction.setText(_translate("MainWindow", "Three-Hump camel", None))
        self.insertOwnFunction.setText(_translate("MainWindow", "Inna funkcja:", None))

